KuaiRand_0501:
    data_root: ../../../FuxiCTR-data
    data_format: npz
    train_data: ../../../FuxiCTR-data/KuaiRand_0501/train.npz
    valid_data: ../../../FuxiCTR-data/KuaiRand_0501/valid.npz
    test_data: ../../../FuxiCTR-data/KuaiRand_0501/test.npz

Beauty_onerec_think:
    data_root: ../../../FuxiCTR-data
    data_format: npz
    train_data: ../../../FuxiCTR-data/Beauty_onerec_think/train.npz
    valid_data: ../../../FuxiCTR-data/Beauty_onerec_think/valid.npz
    test_data: ../../../FuxiCTR-data/Beauty_onerec_think/test.npz

KuaiRec_big:
    data_root: ../../../FuxiCTR-data
    data_format: npz
    train_data: ../../../FuxiCTR-data/KuaiRec_big/train.npz
    valid_data: ../../../FuxiCTR-data/KuaiRec_big/valid.npz
    test_data: ../../../FuxiCTR-data/KuaiRec_big/test.npz